name: Merge CD
run-name: ${{ github.actor }}가 실행함
on:
  pull_request:
    branches:
      - master
  
jobs:
  deploy-and-change-url:
    runs-on: ubuntu-20.04
      outputs: 
        status: ${{ job.status }}
      steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: nodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 16.x

        - name: dependency install
          run: yarn install
        
        - name: chromatic:
          id: chromatic
          uses: chromaui/action@v1
          with:
            projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: changeurl:
          run: gh repo edit --homepage ${{ steps.chromatic.outputs.storybookUrl }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}